Homework3
made-ml-in-prod-2021/vzavadskyi pull request #3
Opened 2021-06-09 21:21 UTC by vzavadskyi

Домашнее задание 3. 
За основу взяты материалы из репозитория https://github.com/made-ml-in-prod-2021/airflow-examples
К soft deadline выполнил не все пункты из задания, прошу дать 2 дня на заверщение таск-листа, прежде чем выставите свои оценки.

Столкнулся с ошибкой, которая не позволила мне выполнить задачи. airflow перестал запускаться. 

ERROR: for webserver  Cannot start service webserver: driver failed programming external connectivity on endpoint airflow_webserver_1 (9f73f53f5ec8632da158aed8e6176f43fa3374b0b7cab6839f2058b02d874496): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use. 

10.06 выполню переустановку ubuntu и продолжу выполнение задач, думаю это рещит мою проблему.

Вроде на занятиях обсуждался вопрос о том, что можно дополнять задания без умножения на штрафной коэффициент уже после soft дедлайна

2021-06-10 17:16 UTC, Mikhail-M commented
Обсуждали вопрос исправления замечения от ревьюера и внесения незначительных изменений, типа комменты и тд.
Делать ползадания, а потом доделывать половину -- это читерство.
Тем более когда речь идет о дз, времени на выполнение которого было ну очень много

2021-06-10 17:29 UTC, SokoloiD commented
Михаил, формально условия нарушены. 
Реально времени на выполнения задание объективно мало, так как наложились довольно тяжелые домашки по NLP , домашка в виде соревнования по CV, домашка  в виде соревнования по машинному обучению на графах. Я про себя пишу.
Я лично смог приступить только в работе только в понедельник и с понедельника я занят тем, что пытаюсь запустить пример из репозитория. На в виртуалбоксе на убунту пример запускается только первый раз. и дальше все. Пришлось установить убунту  на чистую машину. Теперь пример из репозитория не запускается. Все это время уходит не на изучение предмета.  домашка объективно не сложная, а на попытки поднять airflow. Поэтому прошу пощадить всех

2021-06-10 17:45 UTC, vzavadskyi commented
Михал, я подпишусь под каждой просьбой студентов ослабить требования)) Но так же у меня нет вариантов отрицать то, о чем говорите вы. Я против читерства.

2021-06-10 18:05 UTC, Mikhail-M commented
> Михаил, формально условия нарушены.
> Реально времени на выполнения задание объективно мало, так как наложились довольно тяжелые домашки по NLP , домашка в виде соревнования по CV, домашка в виде соревнования по машинному обучению на графах. Я про себя пишу.
> Я лично смог приступить только в работе только в понедельник и с понедельника я занят тем, что пытаюсь запустить пример из репозитория. На в виртуалбоксе на убунту пример запускается только первый раз. и дальше все. Пришлось установить убунту на чистую машину. Теперь пример из репозитория не запускается. Все это время уходит не на изучение предмета. домашка объективно не сложная, а на попытки поднять airflow. Поэтому прошу пощадить всех

Я не согласен, с тем, что поднять airflow по заранее подготовленному docker compose -- непреодолимое препятствие, довольно много людей справились без всяких проблем, кое какие-какие проблемы были у пользователей виндовс, но у ж на unix я достоверно знаю, что это поднимается без особых проблем. Если не подходят мои примеры, то есть официальный docker compose https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html.
Независимо от всяких других дедлайнов, я слабо представляю как 20 дней может быть недостаточным сроком. Возможно сроки как раз таки слишком большие и оставляют слишком много соблазна по отложить на потом. 

Тем не менее много коллег успели в срок, а правила зафиксированы в блоге, поэтому я считаю нечестным ставить полные баллы.

2021-06-10 18:40 UTC, Mikhail-M commented
в общем доделать конечно можно. это в любом случае будет в плюс, но я при формировании оценки это учту

2021-06-14 19:57 UTC, vzavadskyi commented
Добавил тесты и сенсоры. Получается уже вне срока, который я выпрашивал.

2021-06-15 08:49 UTC, SokoloiD commented on README.md
> +| Сумма | 31 | 31 |
Ну формально нужно быть готовым к некторому дисконту 31 * 0.6 = 18.6. Тут уже вопрос  к Михаилу.

2021-06-15 09:08 UTC, SokoloiD requested changes
Нужно пофиксить пути в FileSensor .

2021-06-15 09:08 UTC, SokoloiD commented on dags/generation_data.py
> +    "email": ["airflow@example.com"],
Если алерты не настраивались, то я бы убрал поминание email в настройках

2021-06-15 09:08 UTC, SokoloiD commented on dags/get_predict.py
> +    "email": ["airflow@example.com"],
То же про emil

2021-06-15 09:08 UTC, SokoloiD commented on dags/prepare_model.py
> +    "email": ["airflow@example.com"],
email

2021-06-15 09:08 UTC, SokoloiD commented on dags/prepare_model.py
> +        filepath="/home/vadim/MADE/vzavadskyi/data/raw/data.csv",
Задание пути в таком формате точно работает?  Airflow работает внутри докер контейнера. Есть ли там /home/vadim .....? 
Второй момент:  Путь должен указывать на актуальные данные , то есть содержать код для jinja  {{ ds }}     иначе получается проверка одного и того же файла

2021-06-15 09:08 UTC, SokoloiD commented on dags/prepare_model.py
> +        poke_interval=10,
См предыдущий коммент

2021-06-15 09:08 UTC, SokoloiD commented on images/airflow-download/download.py
> +@click.argument("output_dir")
Я бы аргумент указал --output_dir

2021-06-16 16:17 UTC, vzavadskyi commented on dags/prepare_model.py
> +        filepath="/home/vadim/MADE/vzavadskyi/data/raw/data.csv",
Изменил

2021-06-16 16:17 UTC, vzavadskyi commented on dags/prepare_model.py
> +    "email": ["airflow@example.com"],
Убрал

2021-06-16 16:17 UTC, vzavadskyi commented on dags/get_predict.py
> +    "email": ["airflow@example.com"],
Убрал

2021-06-16 16:17 UTC, vzavadskyi commented on dags/generation_data.py
> +    "email": ["airflow@example.com"],
Убрал

2021-06-16 16:17 UTC, vzavadskyi commented on dags/prepare_model.py
> +        poke_interval=10,
Изменил. + добавил переменную PATH для использования в параметре volumes=[f"{PATH}:/data"]

2021-06-16 16:18 UTC, vzavadskyi commented on images/airflow-download/download.py
> +@click.argument("output_dir")
Изменил.  Как я понял, это общепринятый стандарт?

2021-06-16 19:47 UTC, SokoloiD approved these changes
ок. вопросов нет. исправлено

2021-06-21 08:44 UTC, Mikhail-M commented on dags/get_predict.py
> +import os
За даг 2 баллоа. так как путь до модели берется не из Variables

2021-06-21 08:44 UTC, Mikhail-M approved these changes
Баллы: 29*0.6 = 17.4

2021-06-21 10:09 UTC, SokoloiD commented on dags/get_predict.py
> +import os
Михаил, помогите разобраться. В гите был код, в котором путь до модели брался из переменной окружения. Это даже обсуждалось с ревьюером -Ulia-Demidova . Я по ошибке закрыл pr,  С гитом пока на "Вы". Вероятно из-за этого.  Пишет "Closed with unmerged commits This pull request is closed, but the homework3 branch has unmerged commits." 

Скриншот переписки с Юлией в Аттаче. Сейчас код в репозитории другой код. без использования переменных окружения.

было

try:
    model_path = Variable.get("MODEL_PATH")
except KeyError:
    model_path = "data/model/{{ ds }}/"
...
...
...
        command="--input_dir /data/raw/{{ ds }} --output_dir /data/predictions/{{ds}} --model_dir " + model_path,

![git](https://user-images.githubusercontent.com/46603429/122744786-06234e00-d291-11eb-8394-e9edfe133972.png)

2021-06-27 11:50 UTC, merged